---
jobs:
  - job: tests
    trigger: pull_request
    targets:
      - centos-stream-9-x86_64
      - centos-stream-10-x86_64
    skip_build: true
    tf_extra_params:
      environments:
        - tmt:
            context:
              target_PR_branch: "main"
